name: http-load-testing-staging

on:
  schedule:
    # run every hour
    #- cron: '0 * * * *'
    - cron: '*/5 * * * *'

jobs:
  http-load-test-ordrsmart-request-sample-v2-staging:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat << EOF > loadtest-config.yaml
          url: https://ordrsmart.webflow.io/request-a-sample/request-a-sample-v2
          SLOs:
            http/error-rate: 0
        EOF
    - uses: iter8-tools/iter8-action@v1
      with:
        chart: load-test-http
        valuesFile: loadtest-config.yaml
