name: uptime-monitor-staging

on:
  schedule:
    # run every hour
#     - cron: '0 * * * *'
    - cron: '*/10 * * * *'

jobs:
  ping-ordrsmart-request-sample-v2:
    runs-on: ubuntu-latest
    name: uptime-check-ordrsmart-request-sample-v2
    steps:
    - name: ping-request-sample-v2
      uses: srt32/uptime@v0.2.1
      with:
        url-to-hit: "https://ordrsmart.webflow.io/request-a-sample/request-a-sample-v2"
        expected-statuses: "200"
  ping-ordrsmart-supplier-dashboard:
    runs-on: ubuntu-latest
    name: uptime-check-ordrsmart-supplier-dashboard
    steps:
    - name: ping-supplier-dashboard
      uses: srt32/uptime@v0.2.1
      with:
        url-to-hit: "https://www.ordrsmart.webflow.io/supplier-dashboard"
        expected-statuses: "200"
